#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Aug 30 20:24:49 CDT 2025
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=2
shaderPack=
