#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Aug 11 22:39:03 MSK 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=0
shaderPack=Spooklementary_v2.0.4.zip
enableShaders=true
